ARG IMAGE=python
ARG TAG=3.14-alpine
FROM $IMAGE:$TAG

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ARG PORT=5000
ARG HOST=0.0.0.0

ENV PORT=$PORT
ENV HOST=$HOST

EXPOSE $PORT

CMD ["flask", "run", "--host=$HOST", "--port=$PORT"]